### ISSUE TITLE
[FEATURE] Support for slack deploy hook

### ISSUE THREAD

**Issue by jota12x** [slackapi/python-slack-hooks#42]
**Description of the problem being solved**

Running `slack deploy --experiment=bolt`  requires a hook for deployment. Is this on the roadmap? 
```
(.venv) .venv ❯ slack deploy --experiment=bolt
Check .../logs/slack-debug-20240425.log for full error logs

🚫 A `deploy` hook was not found in the `slack.json` file (sdk_hook_not_found)

Suggestion:

Provide a command or script to run with the deploy command by adding a new hook.
The app will be re-installed to the selected team before invoking this hook.
Both SLACK_APP_TOKEN and SLACK_BOT_TOKEN environment variables will be provided.
```

About `slack deploy`: https://api.slack.com/automation/deploy

**Comment by zimeg** [comment]
Hey @jota12x 👋 Nice find with the `--experiment bolt`! At this time we only have a recommended `deploy` strategy for apps built with the Deno SDK / Deno Hooks, which is deploying to [the Run on Slack infrastructure](https://api.slack.com/concepts/rosi).

The `deploy` hook gives you a way to set or override this strategy with a script or command of your own that can setup production settings however you'd like. This can be something like pushing to a remote branch for Heroku deployment.

Right now we don't have immediate plans to support Python as an additional hosted runtimes, but if this changes then this default `deploy` hook will be updated while project-specific overrides will be preferred! [We'll share updates about these changes too](https://api.slack.com/automation/changelog).

Since we don't have immediate plans for this `deploy` hook I'll go ahead and close this issue, but I hope this is helpful. Of course, feel free to follow up with any additional questions!
